name: flutter_demo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  go_router: ^7.1.1
  intl: any
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  breed_repository:
    path: packages/breed_repository
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.4
  json_serializable: ^6.6.2
  bloc_test: ^9.1.2
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
